version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    container_name: mssqlserver    
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Abc12345      
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data